# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug32
endif
export config

PROJECTS := TerrainRL TerrainRL_Optimizer

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

TerrainRL: 
	@echo "==== Building TerrainRL ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f TerrainRL.make

TerrainRL_Optimizer: 
	@echo "==== Building TerrainRL_Optimizer ($(config)) ===="
	@${MAKE} --no-print-directory -C optimizer -f Makefile

clean:
	@${MAKE} --no-print-directory -C . -f TerrainRL.make clean
	@${MAKE} --no-print-directory -C optimizer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug32"
	@echo "   release32"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TerrainRL"
	@echo "   TerrainRL_Optimizer"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
